version: '2'

volumes:
  orderer.techracers.com:
  peer0.org1.techracers.com:
  peer1.org1.techracers.com:
  peer0.org2.techracers.com:
  peer1.org2.techracers.com:

networks:
  techracers:
services:
  ca0:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org1
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.techracers.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.techracers.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org1.techracers.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerOrg1
    networks:
      - techracers

  ca1:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org2
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.techracers.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org2.techracers.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org2.techracers.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerOrg2
    networks:
      - techracers

  orderer.techracers.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.techracers.com
    container_name: orderer.techracers.com
    networks:
      - techracers

  peer0.org1.techracers.com:
    container_name: peer0.org1.techracers.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org1.techracers.com
    networks:
      - techracers

  peer1.org1.techracers.com:
    container_name: peer1.org1.techracers.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.org1.techracers.com
    networks:
      - techracers

  peer0.org2.techracers.com:
    container_name: peer0.org2.techracers.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org2.techracers.com
    networks:
      - techracers

  peer1.org2.techracers.com:
    container_name: peer1.org2.techracers.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.org2.techracers.com
    networks:
      - techracers
