version: '2'

volumes:
  orderer.yourdomainname.com:
  peer0.org1.yourdomainname.com:
  peer1.org1.yourdomainname.com:
  peer0.org2.yourdomainname.com:
  peer1.org2.yourdomainname.com:

networks:
  yourdomainname:

services:

  orderer.yourdomainname.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.yourdomainname.com
    container_name: orderer.yourdomainname.com
    networks:
      - yourdomainname

  peer0.org1.yourdomainname.com:
    container_name: peer0.org1.yourdomainname.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org1.yourdomainname.com
    environment:
      - CORE_LEDGER_HISTORY_ENABLEHISTORYDATABASE=true
    networks:
      - yourdomainname

  peer1.org1.yourdomainname.com:
    container_name: peer1.org1.yourdomainname.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.org1.yourdomainname.com
    environment:
      - CORE_LEDGER_HISTORY_ENABLEHISTORYDATABASE=true   
    networks:
      - yourdomainname

  peer0.org2.yourdomainname.com:
    container_name: peer0.org2.yourdomainname.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org2.yourdomainname.com
    environment:
      - CORE_LEDGER_HISTORY_ENABLEHISTORYDATABASE=true
    networks:
      - yourdomainname

  peer1.org2.yourdomainname.com:
    container_name: peer1.org2.yourdomainname.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.org2.yourdomainname.com
    environment:
      - CORE_LEDGER_HISTORY_ENABLEHISTORYDATABASE=true
    networks:
      - yourdomainname

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:latest
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.org1.yourdomainname.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.yourdomainname.com/peers/peer0.org1.yourdomainname.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.yourdomainname.com/peers/peer0.org1.yourdomainname.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.yourdomainname.com/peers/peer0.org1.yourdomainname.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.yourdomainname.com/users/Admin@org1.yourdomainname.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.yourdomainname.com
      - peer0.org1.yourdomainname.com
      - peer1.org1.yourdomainname.com
      - peer0.org2.yourdomainname.com
      - peer1.org2.yourdomainname.com
    networks:
      - yourdomainname
